import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
startup_mode = "Maximized"
title = "askfjasflkajf"

[env]
TERM = "xterm-256color"

[font]
size = 10
normal      = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold        = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic      = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true
