import = ["~/.config/alacritty/gruvbox.toml"]

[window]
startup_mode = "Maximized"
title = "maen"

[env]
TERM = "xterm-256color"

[font]
size = 10
normal      = { family = "JetBrainsMono Nerd Font", style = "Normal" }
bold        = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic      = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true
